name: PROS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-22.04
    container: ghcr.io/purduesigbots/pros-cli:latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: pros make
