name: PROS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PROS CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user "pros-cli>=3.5,<4"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pros --version

      - name: Install ARM GCC toolchain
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi \
            libnewlib-arm-none-eabi
          arm-none-eabi-g++ --version

      - name: Build project
        run: pros make
