name: PROS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install PROS CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pros-cli
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pros --version

      - name: Cache PROS toolchains
        uses: actions/cache@v4
        with:
          path: ~/.pros
          key: ${{ runner.os }}-pros-toolchains
          restore-keys: |
            ${{ runner.os }}-pros-

      - name: Build project
        run: pros make
